
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; -- deadlock
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED; --deadlock
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ; --deadlock
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; --deadlock
BEGIN TRANSACTION;

INSERT into liczby2 VALUES (1);

WAITFOR DELAY '00:00:07'

UPDATE liczby1 set liczba = 10;

COMMIT;
